fix(deps): update opensumi packages to v3.0.3 and update webpack 5.x
opensumi/ide-startup pull request #106
Opened 2024-06-14 07:28 UTC by dabaoshu

2024-06-14 08:42 UTC, bytemain commented
👍 Thanks! fantastic work!

2024-06-14 08:45 UTC, bytemain requested changes

2024-06-14 08:45 UTC, bytemain commented on src/browser/render-app.ts
> -  app.start(document.getElementById('main')!, 'web');
createRoot will be used inside the `start` function:
![CleanShot 2024-06-14 at 16 45 33@2x](https://github.com/opensumi/ide-startup/assets/13938334/9df34a69-39d4-486b-9529-af1c818a496f)


so you can revert this change

2024-06-15 03:49 UTC, dabaoshu commented on src/browser/render-app.ts
> -  app.start(document.getElementById('main')!, 'web');
revert this change app.start

2024-06-15 06:05 UTC, bytemain approved these changes

2024-06-17 02:32 UTC, merged