fix: 修复 download.js 脚本在 Windows 创建文件时出现 `?` 非法字符
opensumi/ide-startup pull request #60
Opened 2023-03-15 07:29 UTC by fankangsong

解决在 Windows 执行 `node scripts/download.js` 出现的报错：

```shell
$ node scripts/download.js
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\fanks\AppData\Local\Temp\extension\vscode-extensions.opensumi-default-themes?version=2.5.8'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\fanks\\AppData\\Local\\Temp\\extension\\vscode-extensions.opensumi-default-themes?version=2.5.8'
}
```

2023-03-15 07:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/ide-startup?pullRequest=60) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/ide-startup?pullRequest=60) before we can accept your contribution.<br/><hr/>**fanks** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/ide-startup?pullRequest=60) it.</sub>

2023-03-15 08:31 UTC, erha19 requested changes
LGTM

2023-03-16 02:29 UTC, bk1012 commented
https://github.com/opensumi/core/blob/main/scripts/download.js#L61

这里应该也会有同样的问题，要不要一起提个 PR 😁

2023-03-16 07:36 UTC, erha19 commented on scripts/download.js
> +  const tmpZipFile = path.join(tmpPath, path.basename(url.replace(/\?/, '-')));
@fankangsong 麻烦点击一下这里的 CLA 按钮做一下签署 ~ https://github.com/opensumi/ide-startup/pull/60#issuecomment-1469485869

2023-03-20 04:12 UTC, erha19 commented
@fankangsong 感谢你的提交，麻烦签署一下 CLA 协议 https://github.com/opensumi/ide-startup/pull/60#issuecomment-1469485869

2023-04-06 02:43 UTC, erha19 commented
@fankangsong CLA 文件麻烦签署一下 ~

2023-04-25 06:40 UTC, closed without merging